import type { TrainLineGroup } from "@/types/location";

export const TRAIN_LINE_GROUPS: TrainLineGroup[] = [
  {
    company: "JR東日本",
    lines: [
      {
        id: "yamanote",
        name: "山手線",
        company: "JR東日本",
        stations: [
          { id: "ya-tokyo", name: "東京" },
          { id: "ya-yurakucho", name: "有楽町" },
          { id: "ya-shimbashi", name: "新橋" },
          { id: "ya-hamamatsucho", name: "浜松町" },
          { id: "ya-tamachi", name: "田町" },
          { id: "ya-shinagawa", name: "品川" },
          { id: "ya-osaki", name: "大崎" },
          { id: "ya-gotanda", name: "五反田" },
          { id: "ya-meguro", name: "目黒" },
          { id: "ya-ebisu", name: "恵比寿" },
          { id: "ya-shibuya", name: "渋谷" },
          { id: "ya-harajuku", name: "原宿" },
          { id: "ya-yoyogi", name: "代々木" },
          { id: "ya-shinjuku", name: "新宿" },
          { id: "ya-shin-okubo", name: "新大久保" },
          { id: "ya-takadanobaba", name: "高田馬場" },
          { id: "ya-mejiro", name: "目白" },
          { id: "ya-ikebukuro", name: "池袋" },
          { id: "ya-otsuka", name: "大塚" },
          { id: "ya-sugamo", name: "巣鴨" },
          { id: "ya-komagome", name: "駒込" },
          { id: "ya-tabata", name: "田端" },
          { id: "ya-nishi-nippori", name: "西日暮里" },
          { id: "ya-nippori", name: "日暮里" },
          { id: "ya-uguisudani", name: "鶯谷" },
          { id: "ya-ueno", name: "上野" },
          { id: "ya-okachimachi", name: "御徒町" },
          { id: "ya-akihabara", name: "秋葉原" },
          { id: "ya-kanda", name: "神田" },
        ],
      },
      {
        id: "chuo",
        name: "中央線",
        company: "JR東日本",
        stations: [
          { id: "ch-tokyo", name: "東京" },
          { id: "ch-kanda", name: "神田" },
          { id: "ch-ochanomizu", name: "御茶ノ水" },
          { id: "ch-yotsuya", name: "四ツ谷" },
          { id: "ch-shinjuku", name: "新宿" },
          { id: "ch-nakano", name: "中野" },
          { id: "ch-koenji", name: "高円寺" },
          { id: "ch-asagaya", name: "阿佐ヶ谷" },
          { id: "ch-ogikubo", name: "荻窪" },
          { id: "ch-nishi-ogikubo", name: "西荻窪" },
          { id: "ch-kichijoji", name: "吉祥寺" },
          { id: "ch-mitaka", name: "三鷹" },
          { id: "ch-musashisakai", name: "武蔵境" },
          { id: "ch-higashikoganei", name: "東小金井" },
          { id: "ch-musashikoganei", name: "武蔵小金井" },
          { id: "ch-kokubunji", name: "国分寺" },
          { id: "ch-nishi-kokubunji", name: "西国分寺" },
          { id: "ch-kunitachi", name: "国立" },
          { id: "ch-tachikawa", name: "立川" },
        ],
      },
      {
        id: "sobu",
        name: "総武線",
        company: "JR東日本",
        stations: [
          { id: "so-mitaka", name: "三鷹" },
          { id: "so-kichijoji", name: "吉祥寺" },
          { id: "so-nishi-ogikubo", name: "西荻窪" },
          { id: "so-ogikubo", name: "荻窪" },
          { id: "so-asagaya", name: "阿佐ヶ谷" },
          { id: "so-koenji", name: "高円寺" },
          { id: "so-nakano", name: "中野" },
          { id: "so-higashi-nakano", name: "東中野" },
          { id: "so-okubo", name: "大久保" },
          { id: "so-shinjuku", name: "新宿" },
          { id: "so-yotsuya", name: "四ツ谷" },
          { id: "so-ichigaya", name: "市ヶ谷" },
          { id: "so-iidabashi", name: "飯田橋" },
          { id: "so-suidobashi", name: "水道橋" },
          { id: "so-ochanomizu", name: "御茶ノ水" },
          { id: "so-akihabara", name: "秋葉原" },
          { id: "so-ryogoku", name: "両国" },
          { id: "so-kinshicho", name: "錦糸町" },
          { id: "so-kameido", name: "亀戸" },
          { id: "so-hirai", name: "平井" },
          { id: "so-shin-koiwa", name: "新小岩" },
          { id: "so-koiwa", name: "小岩" },
          { id: "so-ichikawa", name: "市川" },
          { id: "so-motoyawata", name: "本八幡" },
          { id: "so-shimototal", name: "下総中山" },
          { id: "so-nishi-funabashi", name: "西船橋" },
          { id: "so-funabashi", name: "船橋" },
          { id: "so-tsudanuma", name: "津田沼" },
          { id: "so-chiba", name: "千葉" },
        ],
      },
      {
        id: "keihin-tohoku",
        name: "京浜東北線",
        company: "JR東日本",
        stations: [
          { id: "kt-omiya", name: "大宮" },
          { id: "kt-urawa", name: "浦和" },
          { id: "kt-warabi", name: "蕨" },
          { id: "kt-kawaguchi", name: "川口" },
          { id: "kt-akabane", name: "赤羽" },
          { id: "kt-oji", name: "王子" },
          { id: "kt-tabata", name: "田端" },
          { id: "kt-nishi-nippori", name: "西日暮里" },
          { id: "kt-nippori", name: "日暮里" },
          { id: "kt-ueno", name: "上野" },
          { id: "kt-okachimachi", name: "御徒町" },
          { id: "kt-akihabara", name: "秋葉原" },
          { id: "kt-kanda", name: "神田" },
          { id: "kt-tokyo", name: "東京" },
          { id: "kt-yurakucho", name: "有楽町" },
          { id: "kt-shimbashi", name: "新橋" },
          { id: "kt-hamamatsucho", name: "浜松町" },
          { id: "kt-tamachi", name: "田町" },
          { id: "kt-shinagawa", name: "品川" },
          { id: "kt-oimachi", name: "大井町" },
          { id: "kt-omori", name: "大森" },
          { id: "kt-kamata", name: "蒲田" },
          { id: "kt-kawasaki", name: "川崎" },
          { id: "kt-yokohama", name: "横浜" },
        ],
      },
    ],
  },
  {
    company: "東京メトロ",
    lines: [
      {
        id: "ginza",
        name: "銀座線",
        company: "東京メトロ",
        stations: [
          { id: "gz-shibuya", name: "渋谷" },
          { id: "gz-omotesando", name: "表参道" },
          { id: "gz-gaiemmae", name: "外苑前" },
          { id: "gz-aoyama-itchome", name: "青山一丁目" },
          { id: "gz-akasaka-mitsuke", name: "赤坂見附" },
          { id: "gz-tameike-sanno", name: "溜池山王" },
          { id: "gz-toranomon", name: "虎ノ門" },
          { id: "gz-shimbashi", name: "新橋" },
          { id: "gz-ginza", name: "銀座" },
          { id: "gz-kyobashi", name: "京橋" },
          { id: "gz-nihombashi", name: "日本橋" },
          { id: "gz-mitsukoshimae", name: "三越前" },
          { id: "gz-kanda", name: "神田" },
          { id: "gz-suehirocho", name: "末広町" },
          { id: "gz-ueno-hirokoji", name: "上野広小路" },
          { id: "gz-ueno", name: "上野" },
          { id: "gz-inaricho", name: "稲荷町" },
          { id: "gz-tawaramachi", name: "田原町" },
          { id: "gz-asakusa", name: "浅草" },
        ],
      },
      {
        id: "marunouchi",
        name: "丸ノ内線",
        company: "東京メトロ",
        stations: [
          { id: "mn-ogikubo", name: "荻窪" },
          { id: "mn-shin-koenji", name: "新高円寺" },
          { id: "mn-higashi-koenji", name: "東高円寺" },
          { id: "mn-shin-nakano", name: "新中野" },
          { id: "mn-nakano-sakaue", name: "中野坂上" },
          { id: "mn-nishi-shinjuku", name: "西新宿" },
          { id: "mn-shinjuku", name: "新宿" },
          { id: "mn-shinjuku-sanchome", name: "新宿三丁目" },
          { id: "mn-shinjuku-gyoemmae", name: "新宿御苑前" },
          { id: "mn-yotsuya-sanchome", name: "四谷三丁目" },
          { id: "mn-yotsuya", name: "四ツ谷" },
          { id: "mn-akasaka-mitsuke", name: "赤坂見附" },
          { id: "mn-kokkai-gijidomae", name: "国会議事堂前" },
          { id: "mn-kasumigaseki", name: "霞ヶ関" },
          { id: "mn-ginza", name: "銀座" },
          { id: "mn-tokyo", name: "東京" },
          { id: "mn-otemachi", name: "大手町" },
          { id: "mn-awajicho", name: "淡路町" },
          { id: "mn-ochanomizu", name: "御茶ノ水" },
          { id: "mn-hongo-sanchome", name: "本郷三丁目" },
          { id: "mn-korakuen", name: "後楽園" },
          { id: "mn-myogadani", name: "茗荷谷" },
          { id: "mn-shin-otsuka", name: "新大塚" },
          { id: "mn-ikebukuro", name: "池袋" },
        ],
      },
      {
        id: "hibiya",
        name: "日比谷線",
        company: "東京メトロ",
        stations: [
          { id: "hb-naka-meguro", name: "中目黒" },
          { id: "hb-ebisu", name: "恵比寿" },
          { id: "hb-hiroo", name: "広尾" },
          { id: "hb-roppongi", name: "六本木" },
          { id: "hb-kamiyacho", name: "神谷町" },
          { id: "hb-kasumigaseki", name: "霞ヶ関" },
          { id: "hb-hibiya", name: "日比谷" },
          { id: "hb-ginza", name: "銀座" },
          { id: "hb-higashi-ginza", name: "東銀座" },
          { id: "hb-tsukiji", name: "築地" },
          { id: "hb-hatchobori", name: "八丁堀" },
          { id: "hb-kayabacho", name: "茅場町" },
          { id: "hb-ningyocho", name: "人形町" },
          { id: "hb-kodemmacho", name: "小伝馬町" },
          { id: "hb-akihabara", name: "秋葉原" },
          { id: "hb-naka-okachimachi", name: "仲御徒町" },
          { id: "hb-ueno", name: "上野" },
          { id: "hb-iriya", name: "入谷" },
          { id: "hb-minowa", name: "三ノ輪" },
          { id: "hb-minami-senju", name: "南千住" },
          { id: "hb-kita-senju", name: "北千住" },
        ],
      },
      {
        id: "tozai",
        name: "東西線",
        company: "東京メトロ",
        stations: [
          { id: "tz-nakano", name: "中野" },
          { id: "tz-ochiai", name: "落合" },
          { id: "tz-takadanobaba", name: "高田馬場" },
          { id: "tz-waseda", name: "早稲田" },
          { id: "tz-kagurazaka", name: "神楽坂" },
          { id: "tz-iidabashi", name: "飯田橋" },
          { id: "tz-kudanshita", name: "九段下" },
          { id: "tz-takebashi", name: "竹橋" },
          { id: "tz-otemachi", name: "大手町" },
          { id: "tz-nihombashi", name: "日本橋" },
          { id: "tz-kayabacho", name: "茅場町" },
          { id: "tz-monzen-nakacho", name: "門前仲町" },
          { id: "tz-kiba", name: "木場" },
          { id: "tz-toyocho", name: "東陽町" },
          { id: "tz-minami-sunamachi", name: "南砂町" },
          { id: "tz-nishi-kasai", name: "西葛西" },
          { id: "tz-kasai", name: "葛西" },
          { id: "tz-urayasu", name: "浦安" },
          { id: "tz-nishi-funabashi", name: "西船橋" },
        ],
      },
      {
        id: "chiyoda",
        name: "千代田線",
        company: "東京メトロ",
        stations: [
          { id: "cy-yoyogi-uehara", name: "代々木上原" },
          { id: "cy-yoyogi-koen", name: "代々木公園" },
          { id: "cy-meiji-jingumae", name: "明治神宮前" },
          { id: "cy-omotesando", name: "表参道" },
          { id: "cy-nogizaka", name: "乃木坂" },
          { id: "cy-akasaka", name: "赤坂" },
          { id: "cy-kokkai-gijidomae", name: "国会議事堂前" },
          { id: "cy-kasumigaseki", name: "霞ヶ関" },
          { id: "cy-hibiya", name: "日比谷" },
          { id: "cy-nijubashimae", name: "二重橋前" },
          { id: "cy-otemachi", name: "大手町" },
          { id: "cy-shin-ochanomizu", name: "新御茶ノ水" },
          { id: "cy-yushima", name: "湯島" },
          { id: "cy-nezu", name: "根津" },
          { id: "cy-sendagi", name: "千駄木" },
          { id: "cy-nishi-nippori", name: "西日暮里" },
          { id: "cy-machiya", name: "町屋" },
          { id: "cy-kita-senju", name: "北千住" },
        ],
      },
      {
        id: "yurakucho",
        name: "有楽町線",
        company: "東京メトロ",
        stations: [
          { id: "yr-wakoshi", name: "和光市" },
          { id: "yr-chikatetsu-narimasu", name: "地下鉄成増" },
          { id: "yr-chikatetsu-akatsuka", name: "地下鉄赤塚" },
          { id: "yr-heiwadai", name: "平和台" },
          { id: "yr-hikawadai", name: "氷川台" },
          { id: "yr-kotake-mukaihara", name: "小竹向原" },
          { id: "yr-senkawa", name: "千川" },
          { id: "yr-kanamecho", name: "要町" },
          { id: "yr-ikebukuro", name: "池袋" },
          { id: "yr-higashi-ikebukuro", name: "東池袋" },
          { id: "yr-gokokuji", name: "護国寺" },
          { id: "yr-edogawabashi", name: "江戸川橋" },
          { id: "yr-iidabashi", name: "飯田橋" },
          { id: "yr-ichigaya", name: "市ヶ谷" },
          { id: "yr-kojimachi", name: "麹町" },
          { id: "yr-nagatacho", name: "永田町" },
          { id: "yr-sakuradamon", name: "桜田門" },
          { id: "yr-yurakucho", name: "有楽町" },
          { id: "yr-ginza-itchome", name: "銀座一丁目" },
          { id: "yr-shintomicho", name: "新富町" },
          { id: "yr-tsukishima", name: "月島" },
          { id: "yr-toyosu", name: "豊洲" },
          { id: "yr-tatsumi", name: "辰巳" },
          { id: "yr-shin-kiba", name: "新木場" },
        ],
      },
      {
        id: "hanzomon",
        name: "半蔵門線",
        company: "東京メトロ",
        stations: [
          { id: "hz-shibuya", name: "渋谷" },
          { id: "hz-omotesando", name: "表参道" },
          { id: "hz-aoyama-itchome", name: "青山一丁目" },
          { id: "hz-nagatacho", name: "永田町" },
          { id: "hz-hanzomon", name: "半蔵門" },
          { id: "hz-kudanshita", name: "九段下" },
          { id: "hz-jimbocho", name: "神保町" },
          { id: "hz-otemachi", name: "大手町" },
          { id: "hz-mitsukoshimae", name: "三越前" },
          { id: "hz-suitengumae", name: "水天宮前" },
          { id: "hz-kiyosumi-shirakawa", name: "清澄白河" },
          { id: "hz-sumiyoshi", name: "住吉" },
          { id: "hz-kinshicho", name: "錦糸町" },
          { id: "hz-oshiage", name: "押上" },
        ],
      },
      {
        id: "namboku",
        name: "南北線",
        company: "東京メトロ",
        stations: [
          { id: "nb-meguro", name: "目黒" },
          { id: "nb-shirokanedai", name: "白金台" },
          { id: "nb-shirokanetakanawa", name: "白金高輪" },
          { id: "nb-azabu-juban", name: "麻布十番" },
          { id: "nb-roppongi-itchome", name: "六本木一丁目" },
          { id: "nb-tameike-sanno", name: "溜池山王" },
          { id: "nb-nagatacho", name: "永田町" },
          { id: "nb-yotsuya", name: "四ツ谷" },
          { id: "nb-ichigaya", name: "市ヶ谷" },
          { id: "nb-iidabashi", name: "飯田橋" },
          { id: "nb-korakuen", name: "後楽園" },
          { id: "nb-todaimae", name: "東大前" },
          { id: "nb-hon-komagome", name: "本駒込" },
          { id: "nb-komagome", name: "駒込" },
          { id: "nb-nishigahara", name: "西ヶ原" },
          { id: "nb-oji", name: "王子" },
          { id: "nb-oji-kamiya", name: "王子神谷" },
          { id: "nb-shimo", name: "志茂" },
          { id: "nb-akabane-iwabuchi", name: "赤羽岩淵" },
        ],
      },
      {
        id: "fukutoshin",
        name: "副都心線",
        company: "東京メトロ",
        stations: [
          { id: "fk-wakoshi", name: "和光市" },
          { id: "fk-chikatetsu-narimasu", name: "地下鉄成増" },
          { id: "fk-chikatetsu-akatsuka", name: "地下鉄赤塚" },
          { id: "fk-heiwadai", name: "平和台" },
          { id: "fk-hikawadai", name: "氷川台" },
          { id: "fk-kotake-mukaihara", name: "小竹向原" },
          { id: "fk-senkawa", name: "千川" },
          { id: "fk-kanamecho", name: "要町" },
          { id: "fk-ikebukuro", name: "池袋" },
          { id: "fk-zoshigaya", name: "雑司が谷" },
          { id: "fk-nishi-waseda", name: "西早稲田" },
          { id: "fk-higashi-shinjuku", name: "東新宿" },
          { id: "fk-shinjuku-sanchome", name: "新宿三丁目" },
          { id: "fk-kita-sando", name: "北参道" },
          { id: "fk-meiji-jingumae", name: "明治神宮前" },
          { id: "fk-shibuya", name: "渋谷" },
        ],
      },
    ],
  },
  {
    company: "都営地下鉄",
    lines: [
      {
        id: "asakusa-line",
        name: "浅草線",
        company: "都営地下鉄",
        stations: [
          { id: "as-nishi-magome", name: "西馬込" },
          { id: "as-magome", name: "馬込" },
          { id: "as-nakanobu", name: "中延" },
          { id: "as-togoshi", name: "戸越" },
          { id: "as-gotanda", name: "五反田" },
          { id: "as-takanawadai", name: "高輪台" },
          { id: "as-sengakuji", name: "泉岳寺" },
          { id: "as-mita", name: "三田" },
          { id: "as-daimon", name: "大門" },
          { id: "as-shimbashi", name: "新橋" },
          { id: "as-higashi-ginza", name: "東銀座" },
          { id: "as-takaracho", name: "宝町" },
          { id: "as-nihombashi", name: "日本橋" },
          { id: "as-ningyocho", name: "人形町" },
          { id: "as-higashi-nihombashi", name: "東日本橋" },
          { id: "as-asakusabashi", name: "浅草橋" },
          { id: "as-kuramae", name: "蔵前" },
          { id: "as-asakusa", name: "浅草" },
          { id: "as-oshiage", name: "押上" },
        ],
      },
      {
        id: "mita-line",
        name: "三田線",
        company: "都営地下鉄",
        stations: [
          { id: "mt-meguro", name: "目黒" },
          { id: "mt-shirokanetakanawa", name: "白金高輪" },
          { id: "mt-shirokanedai", name: "白金台" },
          { id: "mt-mita", name: "三田" },
          { id: "mt-shibakoen", name: "芝公園" },
          { id: "mt-onarimon", name: "御成門" },
          { id: "mt-uchisaiwaicho", name: "内幸町" },
          { id: "mt-hibiya", name: "日比谷" },
          { id: "mt-otemachi", name: "大手町" },
          { id: "mt-jimbocho", name: "神保町" },
          { id: "mt-suidobashi", name: "水道橋" },
          { id: "mt-kasuga", name: "春日" },
          { id: "mt-hakusan", name: "白山" },
          { id: "mt-sengoku", name: "千石" },
          { id: "mt-sugamo", name: "巣鴨" },
          { id: "mt-nishi-sugamo", name: "西巣鴨" },
          { id: "mt-shin-itabashi", name: "新板橋" },
          { id: "mt-itabashi-kuyakushomae", name: "板橋区役所前" },
          { id: "mt-itabashi-honcho", name: "板橋本町" },
          { id: "mt-motohasunuma", name: "本蓮沼" },
          { id: "mt-shimura-sakaue", name: "志村坂上" },
          { id: "mt-shimura-sanchome", name: "志村三丁目" },
          { id: "mt-hasune", name: "蓮根" },
          { id: "mt-nishi-takashimadaira", name: "西高島平" },
        ],
      },
      {
        id: "shinjuku-line",
        name: "新宿線",
        company: "都営地下鉄",
        stations: [
          { id: "sj-shinjuku", name: "新宿" },
          { id: "sj-shinjuku-sanchome", name: "新宿三丁目" },
          { id: "sj-akebonobashi", name: "曙橋" },
          { id: "sj-ichigaya", name: "市ヶ谷" },
          { id: "sj-kudanshita", name: "九段下" },
          { id: "sj-jimbocho", name: "神保町" },
          { id: "sj-ogawamachi", name: "小川町" },
          { id: "sj-iwamotocho", name: "岩本町" },
          { id: "sj-bakuro-yokoyama", name: "馬喰横山" },
          { id: "sj-hamacho", name: "浜町" },
          { id: "sj-morishita", name: "森下" },
          { id: "sj-kikukawa", name: "菊川" },
          { id: "sj-sumiyoshi", name: "住吉" },
          { id: "sj-nishi-ojima", name: "西大島" },
          { id: "sj-ojima", name: "大島" },
          { id: "sj-higashi-ojima", name: "東大島" },
          { id: "sj-funabori", name: "船堀" },
          { id: "sj-ichinoe", name: "一之江" },
          { id: "sj-mizue", name: "瑞江" },
          { id: "sj-shinozaki", name: "篠崎" },
          { id: "sj-motoyawata", name: "本八幡" },
        ],
      },
      {
        id: "oedo",
        name: "大江戸線",
        company: "都営地下鉄",
        stations: [
          { id: "oe-shinjuku-nishiguchi", name: "新宿西口" },
          { id: "oe-higashi-shinjuku", name: "東新宿" },
          { id: "oe-wakamatsu-kawada", name: "若松河田" },
          { id: "oe-ushigome-kagurazaka", name: "牛込神楽坂" },
          { id: "oe-iidabashi", name: "飯田橋" },
          { id: "oe-kasuga", name: "春日" },
          { id: "oe-hongo-sanchome", name: "本郷三丁目" },
          { id: "oe-ueno-okachimachi", name: "上野御徒町" },
          { id: "oe-shin-okachimachi", name: "新御徒町" },
          { id: "oe-kuramae", name: "蔵前" },
          { id: "oe-ryogoku", name: "両国" },
          { id: "oe-morishita", name: "森下" },
          { id: "oe-kiyosumi-shirakawa", name: "清澄白河" },
          { id: "oe-monzen-nakacho", name: "門前仲町" },
          { id: "oe-tsukishima", name: "月島" },
          { id: "oe-kachidoki", name: "勝どき" },
          { id: "oe-tsukijishijo", name: "築地市場" },
          { id: "oe-shiodome", name: "汐留" },
          { id: "oe-daimon", name: "大門" },
          { id: "oe-akabanebashi", name: "赤羽橋" },
          { id: "oe-azabu-juban", name: "麻布十番" },
          { id: "oe-roppongi", name: "六本木" },
          { id: "oe-aoyama-itchome", name: "青山一丁目" },
          { id: "oe-kokkai-gijidomae", name: "国立競技場" },
          { id: "oe-yoyogi", name: "代々木" },
          { id: "oe-shinjuku", name: "新宿" },
          { id: "oe-tochomae", name: "都庁前" },
          { id: "oe-nishi-shinjuku-gochome", name: "西新宿五丁目" },
          { id: "oe-nakano-sakaue", name: "中野坂上" },
          { id: "oe-higashi-nakano", name: "東中野" },
          { id: "oe-nakai", name: "中井" },
          { id: "oe-ochiai-minami-nagasaki", name: "落合南長崎" },
          { id: "oe-shin-egota", name: "新江古田" },
          { id: "oe-nerima", name: "練馬" },
          { id: "oe-toshimaen", name: "豊島園" },
          { id: "oe-nerima-kasugacho", name: "練馬春日町" },
          { id: "oe-hikawadai", name: "光が丘" },
        ],
      },
    ],
  },
];
